"""Build local UI fonts. Requires fonttools[woff]; see docs/FONTS.md."""
import argparse
import hashlib
import json
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'assets/vendor/fonts'


def ranges(points):
    groups = []
    for point in sorted(points):
        if groups and point == groups[-1][1] + 1:
            groups[-1][1] = point
        else:
            groups.append([point, point])
    return ','.join(f'U+{a:X}' if a == b else f'U+{a:X}-{b:X}' for a, b in groups)


def build(source, points, name, filename):
    font = TTFont(source)
    options = subset.Options()
    options.name_IDs = ['*']
    options.name_legacy = True
    options.name_languages = ['*']
    options.hinting = False
    sub = subset.Subsetter(options=options)
    sub.populate(unicodes=points)
    sub.subset(font)
    for table in font['cmap'].tables:
        if table.isUnicode():
            table.cmap = {code: glyph for code, glyph in table.cmap.items() if code in points}
    # Renamed subsets; original copyright and licence metadata are retained.
    ps_name = name.replace(' ', '') + '-Regular'
    for record in font['name'].names:
        if record.nameID in (1, 4, 16):
            record.string = name.encode(record.getEncoding())
        elif record.nameID in (2, 17):
            record.string = 'Regular'.encode(record.getEncoding())
        elif record.nameID in (3, 6):
            record.string = ps_name.encode(record.getEncoding())
    if 'CFF ' in font:
        cff = font['CFF '].cff
        cff.fontNames = [ps_name]
        for top in cff.topDictIndex:
            top.FamilyName = name
            top.FullName = name
    font.flavor = 'woff2'
    target = OUT / filename
    font.save(target)
    actual = set(TTFont(target).getBestCmap())
    assert actual == set(points), f'Lost glyphs: {points - actual}'
    return {'file': filename, 'bytes': target.stat().st_size, 'glyphs': len(actual),
            'unicodeRange': ranges(actual), 'sha256': hashlib.sha256(target.read_bytes()).hexdigest()}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--ui-source', type=Path, required=True)
    parser.add_argument('--ui-bold-source', type=Path, required=True)
    parser.add_argument('--geist-source', type=Path, required=True)
    args = parser.parse_args()
    OUT.mkdir(parents=True, exist_ok=True)
    source_map = set(TTFont(args.ui_source).getBestCmap())
    files = [ROOT / 'index.html', *sorted((ROOT / 'assets').glob('*.js'))]
    ui_text = ''.join(file.read_text(encoding='utf-8') for file in files)
    core = (set(range(32, 256)) | {ord(c) for c in ui_text}) & source_map
    entries = [build(args.ui_source, core, 'Atlas UI', 'atlas-ui-core.woff2')]
    # The theme ships the static UI subset only. Dynamic server names and
    # country names fall back to the platform CJK font, keeping first load
    # small and avoiding a request per arbitrary node name.
    bold = build(args.ui_bold_source, core, 'Atlas UI', 'atlas-ui-semibold.woff2')
    geist_map = set(TTFont(args.geist_source).getBestCmap())
    display_points = (set(range(32, 256)) | {ord(c) for c in ui_text}) & geist_map
    display = build(args.geist_source, display_points, 'Atlas Pixel Display', 'atlas-pixel-display.woff2')
    # Generated declarations are inlined in style.css: no additional CSS request.
    css = ['/* Local WOFF2 subsets; generated by tools/subset-fonts.py. */']
    for entry in [*entries, bold, display]:
        family = 'Atlas Pixel Display' if entry is display else 'Atlas UI'
        weight = '600 900' if entry is bold else '400'
        css.append('@font-face{font-family:"%s";src:url("./vendor/fonts/%s") format("woff2");font-weight:%s;font-style:normal;font-display:swap;unicode-range:%s}' % (family, entry['file'], weight, entry['unicodeRange']))
    css.append('/* End generated font faces. */')
    path = ROOT / 'assets/style.css'
    style = path.read_text(encoding='utf-8')
    if style.startswith('/* Local WOFF2 subsets;'):
        style = style.split('/* End generated font faces. */', 1)[1].lstrip()
    path.write_text('\n'.join(css) + '\n' + style, encoding='utf-8')
    manifest = {'sarasaRelease': 'v1.0.41', 'uiSourceSHA256': hashlib.sha256(args.ui_source.read_bytes()).hexdigest(),
                'geistSourceSHA256': hashlib.sha256(args.geist_source.read_bytes()).hexdigest(),
                'ui': entries, 'semibold': bold, 'display': display,
                'dynamicCjk': 'platform-fallback'}
    (OUT / 'manifest.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    print(json.dumps({'uiCoreBytes': entries[0]['bytes'], 'uiCoreGlyphs': entries[0]['glyphs'], 'uiAllGlyphs': len(source_map),
                      'uiChunks': len(entries), 'boldBytes': bold['bytes'], 'displayBytes': display['bytes'], 'totalFontBytes': sum(e['bytes'] for e in entries) + display['bytes'] + bold['bytes']}))


if __name__ == '__main__':
    main()
